[package]
name = "tongsuo-src"
version = "850.0.3+8.5.0-pre1"
edition = "2024"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/VEY-OSS/tongsuo-src-rs"
description = """
Source of Tongsuo and logic to build it.
"""
exclude = [
  '.github',
  '.gitignore',
  '.gitmodules',
  'ci',

  'tongsuo/fuzz/corpora/*',
  'tongsuo/test/recipes/*',
  'tongsuo/rpm/*',
  'tongsuo/.gitattributes',

  'tongsuo/test',
  'tongsuo/fuzz',
]

[features]
default = []
# Forces configuring Engine module support.
force-engine = []
# Enable kTLS support
ktls = []
# Disable DSO API support
no-dso = []

[workspace]
members = ['testcrate']
exclude = ['target']

[dependencies]
cc = "1.0.79"
